language: python
python: '2.7'
sudo: false
cache:
  directories:
  - eggs
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- mkdir -p build/html
- python bootstrap.py -c plone-$PLONE_VERSION.cfg
- bin/buildout -N -t 3 -c plone-$PLONE_VERSION.cfg
before_script:
- gem install --version 0.8.9 faraday
- gem install travis-artifacts
script:
- bin/pybot source/desktop
after_script:
- bin/sphinx-build -b html source build/html
- travis-artifacts upload --path build/html
- travis-artifacts upload --target-path latest --path build/html
env:
  - PLONE_VERSION=5.x
  - PLONE_VERSION=4.x
  global:
  - ARTIFACTS_S3_BUCKET=plone.themepreview
  - secure: i7LN43fLQvERhIHSPaz8xp4KUX0bAslkq7rp3khlCZbAN7QD/W9FfNwu4EkmgvXrU87/rQlWknRQC8BhBhHlPuzZU2gdO9jNq6e0z7RD+Gx37z5l5gDDxTRaxKpkPeE/z/wcP5MG4021oGWkPC0Y9qYl0nM9R9umbckGqrAQ/vg=
  - secure: T8YQL8dSZA+/akDGhVP5X6ajcq/4QV/TB7MizftCovS/u3fkr9T1ls2tS847IdqEzAKDubb1xhqzAyTPd0aIt6eSvYA76VM19SLKWN5ozUH7xjdLrxy4jTIDc3ivLiwMG3v3ASHmRV43Wzh9/Y+Q7ArS2Bsi7+Kdx9EtJZBdfyc=
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-docs
    template:
    - ! '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
    - ! 'Sphinx: http://plone.themepreview.s3-website-us-east-1.amazonaws.com/artifacts/%{build_number}/%{build_number}.1/'
